# Generated by Django 3.2.12 on 2022-03-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_auto_20220308_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lot',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
