# Generated by Django 3.2.12 on 2022-03-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0004_auto_20220314_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
