# Generated by Django 3.2.12 on 2022-03-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0009_lotimage_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotimage',
            name='file_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
