# Generated by Django 3.2.12 on 2022-03-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0010_lotimage_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
