# Generated by Django 3.2.12 on 2022-03-17 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('lots', '0011_auction_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='lot',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.cart'),
        ),
    ]
