# Generated by Django 3.2.12 on 2022-03-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0012_auto_20220317_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
