# Generated by Django 3.2.12 on 2022-03-19 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_cart_order'),
        ('lots', '0013_lot_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.order'),
        ),
    ]
