# Generated by Django 3.2.12 on 2022-03-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20220318_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_session_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
