# Generated by Django 3.2.12 on 2022-03-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20220322_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stripe_json_event_obj',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
