# Generated by Django 3.2.12 on 2022-03-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_stripe_json_event_obj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_json_event_obj',
            new_name='stripe_sesion_data',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_message',
        ),
    ]
