# Generated by Django 3.2.12 on 2022-03-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_rename_stripe_sesion_data_order_stripe_session_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='strip_payment_data',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
