# Generated by Django 3.2.12 on 2022-03-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20220323_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='strip_payment_data',
            new_name='stripe_payment_data',
        ),
    ]
