# Generated by Django 3.2.12 on 2022-03-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_rename_strip_payment_data_order_stripe_payment_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_last_four',
            field=models.CharField(default='4444', max_length=5),
            preserve_default=False,
        ),
    ]
