# Generated by Django 3.2.12 on 2022-03-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_stripe_last_four'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_payment_status',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='stripe_last_four',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
